### ISSUE TITLE
Inference of pre-trained network.

### ISSUE THREAD

**Issue by Nandan532189** [amirgholami/SqueezeNext#1]
Can we convert train_val.prototxt to deploy.prototxt for inference purpose ?

**Comment by amirgholami** [comment]
Yes it is possible. You need to remove the data layer (both test and train) and also remove the accuracy/loss layers at the end. For instruction please see below:

https://github.com/BVLC/caffe/wiki/Using-a-Trained-Network:-Deploy

**Comment by Nandan532189** [comment]
Thanks for quick reply.
It's working.
