### ISSUE TITLE
Difference between 1x_v1 and 1x_v1-G version of squeezenext

### ISSUE THREAD

**Issue by Jayan-K-Duggal** [amirgholami/SqueezeNext#8]
Difference between 1x_v1 and 1x_v1-G version of squeeze next, why you are getting better accuracy on G version. Do you have results for CIFAR-10 dataset?

**Comment by amirgholami** [comment]
The different in the G version is the use of group convolution. You can actually visualize the networks by copy/pasting train_val.prototxt for each model here:

http://ethereon.github.io/netscope/#/editor

For links to Cifar-10 please see updated README.md in the repo
